apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecoscape-pvc
  namespace: load
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
